### ISSUE TITLE
Postfix should handle rejections correctly

### ISSUE THREAD

**Issue by unxs0** [ingadhoc/adhoc-rancher#5]
If email is rejected Postfix should handle server chatter correctly. This may involve Postfix node data replication, e.g. any Postfix service should be able handle rejection since we will probably need to load balance input to Postfix or MX/A record round robin at least. TBD.

**Comment by unxs0** [comment]
What needs to happen exactly?
Idea 1: Postfix needs to accept rejection email, so  it needs to know the names of domains it accepts email for.

**Comment by unxs0** [comment]
Usually all mail is relayed via a service like sendgrid. Looking at best practices now.

**Comment by unxs0** [comment]
How it works now:

postfix accepts email runs openerp_mailgate.py fails and sends non delivery notification email via sendgrid.

Details:


```
root@host1:~# telnet 10.42.82.126 25
Trying 10.42.82.126...
Connected to 10.42.82.126.
Escape character is '^]'.
220 mail.sistemasadhoc.com ESMTP Postfix (Ubuntu)
ehlo root@host1.sistemasadhoc.com
250-mail.sistemasadhoc.com
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
mail from:  root@host1.sistemasadhoc.com
250 2.1.0 Ok
rcpt to: basquet@basquet.sistemasadhoc.com
250 2.1.5 Ok
data
354 End data with <CR><LF>.<CR><LF>
Testing 1234567890


1234567890
.
250 2.0.0 Ok: queued as 09B39665
quit
221 2.0.0 Bye


```
```
Apr 24 12:39:01 11ad5d825bab postfix/smtpd[594]: connect from unknown[10.42.0.1]
Apr 24 12:40:03 11ad5d825bab postfix/smtpd[594]: 09B39665: client=unknown[10.42.0.1]
Apr 24 12:40:05 11ad5d825bab postfix/anvil[571]: statistics: max connection rate 1/60s for (smtp:::1) at Apr 24 12:35:37
Apr 24 12:40:05 11ad5d825bab postfix/anvil[571]: statistics: max connection count 1 for (smtp:::1) at Apr 24 12:35:37
Apr 24 12:40:05 11ad5d825bab postfix/anvil[571]: statistics: max cache size 1 at Apr 24 12:35:37
Apr 24 12:40:21 11ad5d825bab postfix/cleanup[606]: 09B39665: message-id=<>
Apr 24 12:40:21 11ad5d825bab postfix/qmgr[172]: 09B39665: from=<root@host1.sistemasadhoc.com>, size=247, nrcpt=1 (queue active)
Apr 24 12:40:22 11ad5d825bab postfix/local[607]: 09B39665: to=<basquet.sistemasadhoc.com@localhost>, orig_to=<basquet@basquet.sistemasadhoc.com>, relay=local, delay=38, delays=37/0.03/0/0.46, dsn=5.3.0, status=bounced (Command died with status 1: " /opt/odoo/openerp_mailgate.py  --host=10.42.173.131 --port=8069 -d default". Command output: Traceback (most recent call last):   File "/opt/odoo/openerp_mailgate.py", line 213, in <module>     main()   File "/opt/odoo/openerp_mailgate.py", line 179, in main     email_default=options.default)   File "/opt/odoo/openerp_mailgate.py", line 111, in __init__     'ir.model', 'search', [('model', '=', model)])[0]   File "/opt/odoo/openerp_mailgate.py", line 96, in __call__     self.dbname, self.user_id, self.passwd, *request, **kwargs)   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__     return self.__send(self.__name, args)   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request     verbose=self.__verbose   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request     return self.single_request(host, handler, request_body, verbose)   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request     return self.parse_response(response)   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response     return u.close()   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close     raise Fault(**self._stack[0]) xmlrpclib.Fault: <Fault FATAL:  database "default" does not exist : 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 34, in dispatch\n    security.check(db,uid,passwd)\n  File "/usr/lib/python2.7/dist-packages/openerp/service/security.py", line 12, in check\n    res_users = opener
Apr 24 12:40:22 11ad5d825bab postfix/cleanup[606]: 4EF06674: message-id=<20170424124022.4EF06674@mail.sistemasadhoc.com>
Apr 24 12:40:22 11ad5d825bab postfix/qmgr[172]: 4EF06674: from=<>, size=8907, nrcpt=1 (queue active)
Apr 24 12:40:22 11ad5d825bab postfix/bounce[609]: 09B39665: sender non-delivery notification: 4EF06674
Apr 24 12:40:22 11ad5d825bab postfix/qmgr[172]: 09B39665: removed
Apr 24 12:40:22 11ad5d825bab postfix/smtp[611]: 4EF06674: to=<root@host1.sistemasadhoc.com>, relay=smtp.sendgrid.net[108.168.190.109]:2525, delay=0.48, delays=0/0.1/0.34/0.04, dsn=2.0.0, status=sent (250 Ok: queued as Rcd3ZXuyS_CuPJzqBhaOSQ)
Apr 24 12:40:22 11ad5d825bab postfix/qmgr[172]: 4EF06674: removed
Apr 24 12:40:29 11ad5d825bab postfix/smtpd[594]: disconnect from unknown[10.42.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
```

**Comment by unxs0** [comment]
Do we need to configure this:


```
class DefaultConfig(object):

    OPENERP_DEFAULT_USER_ID = 1
    OPENERP_DEFAULT_PASSWORD = 'admin'
    OPENERP_HOSTNAME = 'localhost'
    OPENERP_PORT = 8069
    OPENERP_DEFAULT_DATABASE = 'openerp'
    MAIL_ERROR = 'error@example.com'
    MAIL_SERVER = 'smtp.example.com'
    MAIL_SERVER_PORT = 25
    MAIL_ADMINS = ('info@example.com',)

config = DefaultConfig()

```

**Comment by unxs0** [comment]
I have configured a mail server and DNS to get all mail for sistemasadhoc.com for debugging this issue.

**Comment by unxs0** [comment]
Looking at production adhoc server config now for details.

**Comment by unxs0** [comment]
Example /etc/aliases config

```
email.adhoc.com.ar: "| /opt/odoo/openerp_mailgate.py  --host=localhost --port=1121 -u 1 -p WiUXXv0T7QcoRhcy69lp -d prod_adhoc
```

**Comment by unxs0** [comment]
It seems like to test we need to have a database and also maybe something else configured in Odoo?

**Comment by unxs0** [comment]
Configure Odoo:

1. default db
2. add app Discuss
3. set developer mode
4. general settings: set email alias domain
5. configure/test outgoing email server
6. ???

**Comment by unxs0** [comment]
Getting closer?

```
Apr 24 15:09:06 5481d9b5784e postfix/smtpd[617]: connect from unknown[10.42.0.1]
Apr 24 15:09:43 5481d9b5784e postfix/smtpd[617]: 8E720614: client=unknown[10.42.0.1]
Apr 24 15:10:20 5481d9b5784e postfix/cleanup[620]: 8E720614: message-id=<>
Apr 24 15:10:20 5481d9b5784e postfix/qmgr[492]: 8E720614: from=<host0@sistemasadhoc.com>, size=317, nrcpt=1 (queue active)
Apr 24 15:10:20 5481d9b5784e postfix/local[644]: 8E720614: to=<basquet.sistemasadhoc.com@localhost>, orig_to=<basquet@basquet.sistemasadhoc.com>, relay=local, delay=52, delays=52/0/0/0.06, dsn=5.3.0, status=bounced (Command died with status 1: " /opt/odoo/openerp_mailgate.py  --host=10.42.89.222 --port=8069 -u 1 -p admin -d default". Command output: Traceback (most recent call last):   File "/opt/odoo/openerp_mailgate.py", line 213, in <module>     main()   File "/opt/odoo/openerp_mailgate.py", line 179, in main     email_default=options.default)   File "/opt/odoo/openerp_mailgate.py", line 111, in __init__     'ir.model', 'search', [('model', '=', model)])[0] IndexError: list index out of range )
Apr 24 15:10:20 5481d9b5784e postfix/cleanup[620]: D0A4262C: message-id=<20170424151020.D0A4262C@mail.sistemasadhoc.com>
Apr 24 15:10:20 5481d9b5784e postfix/qmgr[492]: D0A4262C: from=<>, size=3089, nrcpt=1 (queue active)
Apr 24 15:10:20 5481d9b5784e postfix/bounce[646]: 8E720614: sender non-delivery notification: D0A4262C
Apr 24 15:10:20 5481d9b5784e postfix/qmgr[492]: 8E720614: removed
Apr 24 15:10:21 5481d9b5784e postfix/smtp[648]: D0A4262C: to=<host0@sistemasadhoc.com>, relay=smtp.sendgrid.net[108.168.190.110]:2525, delay=0.36, delays=0/0.01/0.31/0.03, dsn=2.0.0, status=sent (250 Ok: queued as vw0xEyLNS1SmZEVW4CHPWA)
Apr 24 15:10:21 5481d9b5784e postfix/qmgr[492]: D0A4262C: removed
Apr 24 15:10:24 5481d9b5784e postfix/smtpd[617]: disconnect from unknown[10.42.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5

```

**Comment by unxs0** [comment]
What does this mean?

`'ir.model', 'search', [('model', '=', model)])[0] IndexError: list index out of range )`

**Comment by jjscarafia** [comment]
reemplazar por este script https://github.com/ingadhoc/odoo-infrastructure/blob/9.0/infrastructure/models/scripts/openerp_mailgate.py

**Comment by unxs0** [comment]
Test worked: But passwd is the passwd we set at db creation not the ADMIN_PASSWORD env var

**Comment by unxs0** [comment]
Test verified. Closing ticket.


```
Subject
PreBeta Test 7
Date
04/25/2017 12:23:08
From
Author
Message Record Name
PreBeta Test 7
Parent Message
PreBeta Test 7 
Related Document Model
crm.lead
Related Document ID
1
Type
Email
Subtype
Discussions 
Body
Gateway
Recipients
Tracking
Reply-To
My Company Direct Sales <sales@basquet.sistemasadhoc.com>
No threading for answers

Message-Id
<1493133788.58@localhost>
Outgoing mail server

```
